# Generated by Django 5.1.1 on 2024-10-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='choice_txt',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='pu_date',
            new_name='pub_date',
        ),
    ]
